sportsmgmt/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <description>Represents a division within a league for organizing teams</description>
    <label>Division</label>
    <nameField>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject> 

sportsmgmt/main/default/objects/Division__c/fields/League__c.field-meta.xml
<CustomField>
    <fullName>League__c</fullName>
    <description>The league this division belongs to</description>
    <label>League</label>
    <referenceTo>League__c</referenceTo>
    <relationshipLabel>Divisions</relationshipLabel>
    <relationshipName>Divisions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
    <deleteConstraint>Restrict</deleteConstraint>
</CustomField> 

sportsmgmt/main/default/objects/League__c/League__c.object-meta.xml
<CustomObject>
    <description>Represents a sports league that contains multiple teams</description>
    <label>League</label>
    <nameField>
        <label>League Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leagues</pluralLabel>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <description>Professional sports leagues</description>
        <label>Professional League</label>
    </recordTypes>
    <recordTypes>
        <fullName>Amateur</fullName>
        <active>true</active>
        <description>Amateur and recreational leagues</description>
        <label>Amateur League</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject> 

sportsmgmt/main/default/classes/util/DivisionWrapper.cls
/**
 * @description Wrapper class for Division__c records implementing IDivision interface
 * @author Sports Management Team
 * @date 2024
 */
public class DivisionWrapper implements IDivision {
    private Division__c originalRecord;
    private Id divisionId;
    private String divisionName;
    private Id leagueId;
    
    /**
     * Constructor that takes a Division__c record and wraps it
     */
    public DivisionWrapper(Division__c division) {
        if (division != null) {
            this.originalRecord = division;
            this.divisionId = division.Id;
            this.divisionName = division.Name;
            this.leagueId = division.League__c;
        }
    }
    
    /**
     * Constructor for creating new division instances
     */
    public DivisionWrapper(Id id, String name, Id leagueId) {
        this.divisionId = id;
        this.divisionName = name;
        this.leagueId = leagueId;
        this.originalRecord = null;
    }
    
    /**
     * Gets the record Id of the division.
     */
    public Id getId() {
        return this.divisionId;
    }

    /**
     * Gets the name of the division.
     */
    public String getName() {
        return this.divisionName;
    }

    /**
     * Gets the League Id that the division belongs to.
     */
    public Id getLeagueId() {
        return this.leagueId;
    }
    
    /**
     * Gets the original Division__c record if available
     */
    public Division__c getOriginalRecord() {
        return this.originalRecord;
    }
} 