sportsmgmt/main/default/objects/League__c/League__c.object-meta.xml
<CustomObject>
    <description>Represents a sports league that contains multiple teams</description>
    <label>League</label>
    <nameField>
        <label>League Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leagues</pluralLabel>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <description>Professional sports leagues</description>
        <label>Professional League</label>
    </recordTypes>
    <recordTypes>
        <fullName>Amateur</fullName>
        <active>true</active>
        <description>Amateur and recreational leagues</description>
        <label>Amateur League</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject> 

sportsmgmt/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <description>Represents a sports team participating in a league. Holds high-level team information used across sports.</description>
    <pluralLabel>Teams</pluralLabel>
    <nameField>
        <type>Text</type>
        <label>Team Name</label>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject> 

sportsmgmt/main/default/objects/Team__c/fields/League__c.field-meta.xml
<CustomField>
    <fullName>League__c</fullName>
    <description>The league this team belongs to</description>
    <label>League</label>
    <referenceTo>League__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
    <deleteConstraint>Restrict</deleteConstraint>
</CustomField> 

sportsmgmt/main/default/classes/util/TeamWrapper.cls
public class TeamWrapper extends AbstractTeam {
    private Team__c originalRecord;
    
    /**
     * Constructor that takes a Team__c record and wraps it
     */
    public TeamWrapper(Team__c team) {
        super(team.Id, team.Name, team.League__c);
        this.originalRecord = team;
    }
    
    /**
     * Constructor for creating new team instances
     */
    public TeamWrapper(Id id, String name, Id leagueId) {
        super(id, name, leagueId);
        this.originalRecord = null;
    }
    
    /**
     * Gets the original Team__c record if available
     */
    public Team__c getOriginalRecord() {
        return this.originalRecord;
    }
} 